version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    networks:
      - azkaban    
    environment:
      - MYSQL_USER=azkaban
      - MYSQL_PASSWORD=azkaban
      - MYSQL_DATABASE=azkaban
      - MYSQL_ROOT_PASSWORD=wootwoot
    volumes:
      - azkaban-exec-server/create-all-sql-0.1.0-SNAPSHOT.sql:/docker-entrypoint-initdb.d/  
      - /data/volumes/mysql:/var/lib/mysql
     
  executor:
    # build: azkaban-exec-server/.
    image: javachen/azkaban-exec-server
    restart: always
    volumes:
      - /data/bi_etl:/data/bi_etl
      - /data/ods:/data/ods
    depends_on:
      - mysql  
    networks:
      - azkaban  

  webserver:
    image: javachen/azkaban-web-server
    restart: always
    depends_on:
      - mysql 
      - executor
    networks:
      - azkaban   
    ports:
      - "8081:8081"

networks:
  azkaban:
    external: true  