version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0 --lower_case_table_names=1
    ports:
      - "3306:3306"
    networks:
      - azkaban    
    environment:
      - MYSQL_USER=azkaban
      - MYSQL_PASSWORD=azkaban
      - MYSQL_DATABASE=azkaban
      - MYSQL_ROOT_PASSWORD=wootwoot
     
  executor:
    # build: azkaban-exec-server/.
    image: javachen/azkaban-exec-server
    restart: always
    depends_on:
      - mysql  
    networks:
      - azkaban  

  webserver:
    image: javachen/azkaban-web-server
    restart: always
    depends_on:
      - mysql 
      - executor
    networks:
      - azkaban   
    ports:
      - "8443:8443"

networks:
  azkaban:
    external: true  