executor:
    build: azkaban-exec-server/.
    restart: always

webserver:
    build: azkaban-web-server/.
    restart: always
    ports:
        - "8443:8443"
    links:
        - executor:azkaban-exec-server